project:
  type: website
  output-dir: "./docs"    # Changed from _output to docs for GitHub Pages
  post-render: encrypt.r

website:
  title: "PythonDataScientist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



